version: "3"
services:
  frontend:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - rails-assets:/helpy/public
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front
    depends_on:
      - web
      
  web:
    build: 
      context: .
      dockerfile: Dockerfile.helpy
    env_file: .env
    volumes:
      - rails-assets:/helpy/public
    networks:
      - front
      - back
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    networks:
      - back
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  rails-assets:

networks:
  front:
    driver: bridge
  back:
    driver: bridge